# Generated by Django 4.0.4 on 2022-05-26 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('fecha_consulta', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_Consulta', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=255)),
                ('MontoTotal', models.FloatField()),
                ('id_Cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_Lab', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id_med', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_caducidad', models.DateField()),
                ('cvc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.persona')),
                ('fecha_contrato', models.DateTimeField()),
                ('usuario', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('contratado', models.BooleanField()),
                ('correo_institucional', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.persona')),
                ('correo_paciente', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('alergias', models.CharField(max_length=255)),
                ('enfermedades_base', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rayos_X',
            fields=[
                ('id_Rayos', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=255)),
                ('id_Consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consulta')),
                ('id_Lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='PagoReserva',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cita')),
                ('id_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta_Medicina_Receta',
            fields=[
                ('id_Receta', models.AutoField(primary_key=True, serialize=False)),
                ('Desc', models.CharField(max_length=255)),
                ('id_Consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consulta')),
                ('id_Med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicina')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_Servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicio'),
        ),
        migrations.CreateModel(
            name='MedicoEspecialidad',
            fields=[
                ('id_med_esp', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_titulo', models.DateTimeField()),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidad')),
                ('medico_id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
            ],
        ),
    ]
