# Generated by Django 4.0.4 on 2022-05-26 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosConsulta',
            fields=[
                ('id_pago_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('id_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consulta')),
            ],
        ),
    ]
