# Generated by Django 4.0.4 on 2022-05-28 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pagosconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='fecha_contrato',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.persona'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='usuario',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='medicoespecialidad',
            name='fecha_titulo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.persona'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('ci', 'nombre', 'apellido', 'fecha_nacimiento')},
        ),
    ]
