# Generated by Django 4.0.4 on 2022-06-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cita_id_doctor_cita_id_paciente_tarjeta_id_paciente_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set(),
        ),
    ]
