insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (1, 'gchataignier0@ycombinator.com', 'lcandwell0', 'fKeCgDvLc73t', 'sapien', 'neque');
insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (2, 'kbeevis1@amazon.co.uk', 'czincke1', '66wGim', 'sit amet', 'magna vulputate luctus');
insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (3, 'croiz2@salon.com', 'mrobers2', 'f3uDE9', 'luctus et ultrices', 'sed tristique');
insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (4, 'lbrotherhood3@sciencedirect.com', 'mhamp3', 'kyqSHOS', 'luctus', 'tortor');
insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (5, 'jfluck4@google.fr', 'gharden4', 'lUgOTSPLsR', 'duis', 'a');
insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (6, 'pkulvear5@msu.edu', 'tridgedell5', 'PdWQuy2O', 'augue vestibulum', 'mauris morbi');
insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (7, 'bwhyatt6@columbia.edu', 'kbetonia6', 'hDfjGh6RYC', 'convallis morbi', 'in sapien iaculis');
insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (8, 'icuvley7@sitemeter.com', 'tbeloe7', 'URrnSlrQTSWT', 'id justo', 'elementum');
insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (9, 'bbruneton8@pen.io', 'ppesticcio8', 's3YWxmUGgPU', 'ut', 'lacinia sapien');
insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (10, 'erollin9@google.com.br', 'ttruce9', 'fJosHFt0Y0', 'et ultrices posuere', 'volutpat');
insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (11, 'msilvermanna@hibu.com', 'hpennettia', 'B2EFndt6KlsA', 'mattis odio', 'dictumst etiam');
insert into Paciente (id_personaAI, Correo_Paciente, usuario, pass, alergias, enfermedades_base) values (12, 'ltuplingb@wikipedia.org', 'jaeryb', 'LIez98E', 'ultrices vel', 'amet');
